[tox]
isolated_build = True
envlist = py{310,311,312,313}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
setenv = DJANGO_SETTINGS_MODULE = testauth.settings.local

pass_env =
    AA_DB_HOST
    AA_DB_PASSWORD
    AA_DB_PORT
    AA_DB_USER
    AA_DB_NAME
    AA_REDIS
    USE_MYSQL

deps =
    coverage
install_command = python -m pip install -U {opts} {packages}

commands =
    coverage run runtests.py allianceauth_pve -v 2 --debug-mode
    coverage report
    coverage xml