[tox]
requires =
    tox>=4.2
env_list =
    py{313, 312, 311, 310}

[testenv]
deps =
    coverage
pass_env =
    AA_DB_HOST
    AA_DB_NAME
    AA_DB_PASSWORD
    AA_DB_PORT
    AA_DB_USER
    AA_REDIS
    USE_MYSQL
set_env =
    DJANGO_SETTINGS_MODULE = testauth.settings.local
commands =
    coverage run runtests.py allianceauth_pve -v 2 --debug-mode
    coverage report
    coverage xml
install_command = python -m pip install -U {opts} {packages}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
