/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pve/api/rotations/rotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rotations */
        get: operations["allianceauth_pve_api_rotations_list_rotations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/activity/months/{months}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["allianceauth_pve_api_activity_get_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/projects/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["allianceauth_pve_api_projects_list_projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** RotationSchema */
        RotationSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Closed */
            is_closed: boolean;
            /** Closed At */
            closed_at?: string | null;
            /** Number Of Members */
            number_of_members: number;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Total */
            actual_total: number;
            /** Priority */
            priority: number;
            /** Tax Rate */
            tax_rate: number;
        };
        /** ActivitySchema */
        ActivitySchema: {
            /** Helped Setups */
            helped_setups: number;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Total */
            actual_total: number;
        };
        /** FundingProjectSchema */
        FundingProjectSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Goal */
            goal: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Current Total */
            current_total: number;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Percentage */
            actual_percentage: number;
            /** Estimated Missing Percentage */
            estimated_missing_percentage: number;
            /** Number Of Participants */
            number_of_participants: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    allianceauth_pve_api_rotations_list_rotations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationSchema"][];
                };
            };
        };
    };
    allianceauth_pve_api_activity_get_activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                months: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    allianceauth_pve_api_projects_list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingProjectSchema"][];
                };
            };
        };
    };
}
