/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pve/api/buttons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Buttons */
        get: operations["allianceauth_pve_api_list_buttons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rolesetups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Role Setups */
        get: operations["allianceauth_pve_api_list_role_setups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rotations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rotations */
        get: operations["allianceauth_pve_api_rotations_list_rotations"];
        put?: never;
        /** Create Rotation */
        post: operations["allianceauth_pve_api_rotations_create_rotation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rotations/{rotation_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rotation */
        get: operations["allianceauth_pve_api_rotations_get_rotation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Close Rotation */
        patch: operations["allianceauth_pve_api_rotations_close_rotation"];
        trace?: never;
    };
    "/pve/api/rotations/{rotation_id}/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rotation Summary */
        get: operations["allianceauth_pve_api_rotations_get_rotation_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rotations/{rotation_id}/project_summaries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rotation Project Summaries */
        get: operations["allianceauth_pve_api_rotations_get_rotation_project_summaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rotations/{rotation_id}/entries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rotation Entries */
        get: operations["allianceauth_pve_api_entries_get_rotation_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rotations/{rotation_id}/entries/{entry_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rotation Entry */
        get: operations["allianceauth_pve_api_entries_get_rotation_entry"];
        put?: never;
        post?: never;
        /** Delete Rotation Entry */
        delete: operations["allianceauth_pve_api_entries_delete_rotation_entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rotations/{rotation_id}/entries/{entry_id}/roles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rotation Entry Roles */
        get: operations["allianceauth_pve_api_entries_get_rotation_entry_roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/rotations/{rotation_id}/entries/{entry_id}/shares/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rotation Entry Shares */
        get: operations["allianceauth_pve_api_entries_get_rotation_entry_shares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/activity/months/{months}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["allianceauth_pve_api_activity_get_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["allianceauth_pve_api_projects_list_projects"];
        put?: never;
        /** Create Project */
        post: operations["allianceauth_pve_api_projects_create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/projects/{project_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["allianceauth_pve_api_projects_get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/projects/{project_id}/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Summary */
        get: operations["allianceauth_pve_api_projects_get_project_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/projects/{project_id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle Complete Project */
        post: operations["allianceauth_pve_api_projects_toggle_complete_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pve/api/permissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Permissions */
        get: operations["allianceauth_pve_api_permissions_list_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** PveButtonSchema */
        PveButtonSchema: {
            /** Id */
            id: number;
            /** Text */
            text: string;
            /** Amount */
            amount: number;
        };
        /** BaseRoleSetupSchema */
        BaseRoleSetupSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** RotationSchema */
        RotationSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Closed */
            is_closed: boolean;
            /** Closed At */
            closed_at?: string | null;
            /** Number Of Members */
            number_of_members: number;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Total */
            actual_total: number;
            /** Priority */
            priority: number;
            /** Tax Rate */
            tax_rate: number;
        };
        /** NewRotationSchema */
        NewRotationSchema: {
            /** Name */
            name: string;
            /** Priority */
            priority: number;
            /** Tax Rate */
            tax_rate: number;
            /** Max Daily Setups */
            max_daily_setups: number;
            /** Min People Share Setup */
            min_people_share_setup: number;
            /** Entry Buttons */
            entry_buttons: number[];
            /** Roles Setups */
            roles_setups: number[];
        };
        /** CloseRotationSchema */
        CloseRotationSchema: {
            /** Sales Value */
            sales_value: number;
        };
        /** RotationSummarySchema */
        RotationSummarySchema: {
            /** Portrait Url */
            portrait_url: string;
            /** Character Id */
            character_id: number;
            /** Main Character Id */
            main_character_id: number | null;
            /** Character Name */
            character_name: string;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Total */
            actual_total: number;
            /** Helped Setups */
            helped_setups: number;
        };
        /** FundingProjectBasicSchema */
        FundingProjectBasicSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** RotationProjectSummarySchema */
        RotationProjectSummarySchema: {
            project: components["schemas"]["FundingProjectBasicSchema"];
            /** Summary */
            summary: components["schemas"]["SummarySchema"][];
        };
        /** SummarySchema */
        SummarySchema: {
            /** Portrait Url */
            portrait_url: string;
            /** Character Id */
            character_id: number;
            /** Main Character Id */
            main_character_id: number | null;
            /** Character Name */
            character_name: string;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Total */
            actual_total: number;
        };
        /** EntrySchema */
        EntrySchema: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by_character: components["schemas"]["EveCharacterSchema"];
            /** Total User Count */
            total_user_count: number;
            /** Total Site Count */
            total_site_count: number;
            /** Estimated Total */
            estimated_total: number;
            /** Estimated Total After Tax */
            estimated_total_after_tax: number;
            /** Actual Total After Tax */
            actual_total_after_tax: number;
        };
        /** EveCharacterSchema */
        EveCharacterSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Portrait Url */
            portrait_url: string;
        };
        /** EntryDetailsSchema */
        EntryDetailsSchema: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            created_by_character: components["schemas"]["EveCharacterSchema"];
            /** Total User Count */
            total_user_count: number;
            /** Total Site Count */
            total_site_count: number;
            /** Estimated Total */
            estimated_total: number;
            /** Estimated Total After Tax */
            estimated_total_after_tax: number;
            /** Actual Total After Tax */
            actual_total_after_tax: number;
            funding_project: components["schemas"]["FundingProjectBasicSchema"] | null;
            /** Funding Percentage */
            funding_percentage: number;
            /** Rotation Is Closed */
            rotation_is_closed: boolean;
            /** User Can Edit */
            user_can_edit: boolean;
        };
        /** EntryRoleSchema */
        EntryRoleSchema: {
            /** Name */
            name: string;
            /** Value */
            value: number;
            /** Role Approximate Percentage */
            role_approximate_percentage: number;
        };
        /** EntryCharacterSchema */
        EntryCharacterSchema: {
            user_main_character: components["schemas"]["EveCharacterSchema"];
            user_character: components["schemas"]["EveCharacterSchema"];
            /** Role Name */
            role_name: string;
            /** Site Count */
            site_count: number;
            /** Helped Setup */
            helped_setup: boolean;
            /** Estimated Share Total */
            estimated_share_total: number;
            /** Estimated Funding Amount */
            estimated_funding_amount: number;
            /** Actual Share Total */
            actual_share_total: number;
            /** Actual Funding Amount */
            actual_funding_amount: number;
        };
        /** ActivitySchema */
        ActivitySchema: {
            /** Helped Setups */
            helped_setups: number;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Total */
            actual_total: number;
        };
        /** FundingProjectSchema */
        FundingProjectSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Goal */
            goal: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Current Total */
            current_total: number;
            /** Estimated Total */
            estimated_total: number;
            /** Actual Percentage */
            actual_percentage: number;
            /** Estimated Missing Percentage */
            estimated_missing_percentage: number;
            /** Number Of Participants */
            number_of_participants: number;
        };
        /** NewProjectSchema */
        NewProjectSchema: {
            /** Name */
            name: string;
            /** Goal */
            goal: number;
        };
        /** PermissionsSchema */
        PermissionsSchema: {
            /** Main Character Id */
            main_character_id: number;
            /** Access Pve */
            access_pve: boolean;
            /** Manage Entries */
            manage_entries: boolean;
            /** Manage Rotations */
            manage_rotations: boolean;
            /** Manage Funding Projects */
            manage_funding_projects: boolean;
            /** Is Superuser */
            is_superuser: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    allianceauth_pve_api_list_buttons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PveButtonSchema"][];
                };
            };
        };
    };
    allianceauth_pve_api_list_role_setups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseRoleSetupSchema"][];
                };
            };
        };
    };
    allianceauth_pve_api_rotations_list_rotations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationSchema"][];
                };
            };
        };
    };
    allianceauth_pve_api_rotations_create_rotation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRotationSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    allianceauth_pve_api_rotations_get_rotation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_rotations_close_rotation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRotationSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_rotations_get_rotation_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationSummarySchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_rotations_get_rotation_project_summaries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationProjectSummarySchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_entries_get_rotation_entries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntrySchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_entries_get_rotation_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryDetailsSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_entries_delete_rotation_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_entries_get_rotation_entry_roles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryRoleSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_entries_get_rotation_entry_shares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
                rotation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryCharacterSchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_activity_get_activity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                months: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    allianceauth_pve_api_projects_list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingProjectSchema"][];
                };
            };
        };
    };
    allianceauth_pve_api_projects_create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewProjectSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    allianceauth_pve_api_projects_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingProjectSchema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_projects_get_project_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarySchema"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_projects_toggle_complete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    allianceauth_pve_api_permissions_list_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionsSchema"];
                };
            };
        };
    };
}
