import type { ExtendedShareItem, RampancyLevel } from "../EntryTypes";

// 32-bit unsigned upper bound, matching Django's PositiveIntegerField.
const MAX_COUNT = 4_294_967_295;

// Rampancy severity of the site. The cumulative Rampancy after N waves is
// `base * N(N+1)/2`, so completing wave `w` alone is worth `base * w`. `base`
// is a constant multiplier that cancels in the payout ratio (all four levels
// give the same split for the same wave ranges); it only sets the magnitude of
// the raw Rampancy shown in the count column.
export const RAMPANCY_LEVELS: readonly RampancyLevel[] = [
    "minimal",
    "moderate",
    "severe",
    "critical",
];

export const RAMPANCY_LEVEL_BASE: Record<RampancyLevel, number> = {
    minimal: 3,
    moderate: 10,
    severe: 20,
    critical: 40,
};

export const DEFAULT_RAMPANCY_LEVEL: RampancyLevel = "critical";

// Rampancy generated by completing wave `w` at a given severity: `base * w`.
function waveValue(w: number, base: number): number {
    return base * w;
}

interface WaveShare {
    character_id: number;
    start: number;
    end: number;
    valid: boolean;
}

function parseShares(shares: readonly ExtendedShareItem[]): WaveShare[] {
    return shares.map((share) => {
        const start = Math.trunc(Number(share.start_wave));
        const end = Math.trunc(Number(share.end_wave));
        const valid =
            Number.isFinite(start) &&
            Number.isFinite(end) &&
            start >= 1 &&
            end >= start;
        return { character_id: share.character_id, start, end, valid };
    });
}

/**
 * Wave-weighted share counts for "Fabs" mode.
 *
 * Completing wave `w` is worth `base * w`, where `base` comes from the site's
 * Rampancy level. That value is split equally between everyone whose start..end
 * range covers wave `w`. A user's `count` is the running sum of their per-wave
 * slices across the waves they were present for, rounded to a whole number.
 *
 * The result is NOT reduced to lowest terms: the raw accrued Rampancy is kept
 * so a human can add the waves up and check any row. The backend then turns
 * `count` into the payout split (`count * role value / Σ`), so uneven splits
 * across 3+ people cause only sub-ISK rounding drift.
 *
 * Uncovered waves contribute nothing. Invalid ranges (missing, start below 1,
 * or end before start) yield a count of 0.
 */
export function computeWaveCounts(
    shares: readonly ExtendedShareItem[],
    level: RampancyLevel = DEFAULT_RAMPANCY_LEVEL,
): Record<number, number> {
    const base = RAMPANCY_LEVEL_BASE[level] ?? RAMPANCY_LEVEL_BASE[DEFAULT_RAMPANCY_LEVEL];
    const parsed = parseShares(shares);

    const result: Record<number, number> = {};
    for (const s of parsed) {
        result[s.character_id] = 0;
    }

    const valid = parsed.filter((s) => s.valid);
    if (valid.length === 0) {
        return result;
    }

    const maxWave = Math.max(...valid.map((s) => s.end));
    const present = new Array<number>(maxWave + 1).fill(0);
    for (const s of valid) {
        for (let w = s.start; w <= s.end; w++) {
            present[w] += 1;
        }
    }

    for (const s of valid) {
        let total = 0;
        for (let w = s.start; w <= s.end; w++) {
            total += waveValue(w, base) / present[w];
        }
        result[s.character_id] = Math.min(Math.round(total), MAX_COUNT);
    }

    return result;
}
