# Generated by Django 3.2.12 on 2022-04-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotation',
            options={'default_permissions': ('add', 'change', 'view'), 'permissions': [('close', 'Can close rotations')]},
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='accessible_to_states',
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='accessible_to_users',
        ),
    ]
