# Generated by Django 3.2.12 on 2022-04-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0003_auto_20220411_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSetupSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('valid_setups', models.IntegerField()),
            ],
            options={
                'db_table': 'allianceauth_pve_setup_summary',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rotation',
            options={'default_permissions': ('add', 'change', 'view'), 'permissions': [('close_rotation', 'Can close rotations')]},
        ),
    ]
