# Generated by Django 3.2.12 on 2022-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0006_auto_20220416_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='tax_rate',
            field=models.FloatField(default=0, help_text='Tax rate in percentage'),
        ),
    ]
