# Generated by Django 4.0.7 on 2022-09-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0012_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='entry_buttons',
            field=models.ManyToManyField(blank=True, help_text='Button to be shown in the Entry form.', related_name='+', to='allianceauth_pve.pvebutton'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='roles_setups',
            field=models.ManyToManyField(blank=True, help_text='Setup avaiable for loading in the Entry form.', related_name='+', to='allianceauth_pve.rolesetup'),
        ),
    ]
