# Generated by Django 4.0.7 on 2022-09-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0012_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_pve', 'Access PvE: Can access pve pages and be added in entries'), ('manage_entries', 'Manage Entries: Can do CRUD operations with entries'), ('manage_rotations', 'Manage Rotations: Can do CRUD operations with rotations'))},
        ),
        migrations.AlterField(
            model_name='rotation',
            name='entry_buttons',
            field=models.ManyToManyField(blank=True, help_text='Button to be shown in the Entry form.', related_name='+', to='allianceauth_pve.pvebutton'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='roles_setups',
            field=models.ManyToManyField(blank=True, help_text='Setup avaiable for loading in the Entry form.', related_name='+', to='allianceauth_pve.rolesetup'),
        ),
    ]
