# Generated by Django 4.0.7 on 2022-09-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0013_alter_rotation_entry_buttons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('access_pve', 'Access PvE: Can access pve pages and be added in entries'), ('manage_entries', 'Manage Entries: Can do CRUD operations with entries'), ('manage_rotations', 'Manage Rotations: Can do CRUD operations with rotations'))},
        ),
    ]
