# Generated by Django 4.0.7 on 2022-09-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0013_alter_general_options_alter_rotation_entry_buttons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='priority',
            field=models.IntegerField(default=100, help_text='Ordering priority. The higher priorities are in the first positions.'),
        ),
    ]
