# Generated by Django 4.0.7 on 2022-10-05 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0014_alter_rotation_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='estimated_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pvebutton',
            name='amount',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(-1000000000000), django.core.validators.MaxValueValidator(1000000000000)]),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='actual_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
