# Generated by Django 4.0.10 on 2023-07-26 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0017_fundingproject_alter_general_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
