# Generated by Django 4.2.11 on 2024-03-28 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('allianceauth_pve', '0019_fundingproject_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycharacter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ratting_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrycharacter',
            name='user_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ratting_shares', to='eveonline.evecharacter'),
        ),
    ]
