# Generated by Django 4.2.16 on 2024-10-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0020_alter_entrycharacter_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('max_daily_setups', models.PositiveSmallIntegerField(default=1, help_text='The maximum number of helped setup per day. If more are submitted, only this number is counted. 0 for deactivating helped setups.')),
                ('min_people_share_setup', models.PositiveSmallIntegerField(default=3, help_text='The minimum number of users in an entry to consider the helped setup valid.')),
                ('tax_rate', models.FloatField(default=0, help_text='Tax rate in percentage')),
                ('priority', models.IntegerField(default=100, help_text='Ordering priority. The higher priorities are in the first positions.')),
                ('entry_buttons', models.ManyToManyField(blank=True, help_text='Button to be shown in the Entry form.', related_name='+', to='allianceauth_pve.pvebutton')),
                ('roles_setups', models.ManyToManyField(blank=True, help_text='Setup avaiable for loading in the Entry form.', related_name='+', to='allianceauth_pve.rolesetup')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
