# Generated by Django 5.2.12 on 2026-04-12 18:58

from django.db import migrations, models


def set_funding_percentage(apps, schema_editor):
    Entry = apps.get_model('allianceauth_pve.Entry')

    Entry.objects.filter(funding_project__isnull=True).update(funding_percentage=None)


def undo_set_funding_percentage(apps, schema_editor):
    Entry = apps.get_model('allianceauth_pve.Entry')

    Entry.objects.filter(funding_percentage=None).update(funding_percentage=0)


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0021_rotationpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='funding_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvebutton',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.RunPython(
            set_funding_percentage,
            undo_set_funding_percentage,
        ),
    ]
