# Generated by Django 5.2.12 on 2026-04-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0022_alter_entry_funding_percentage_and_more'),
        ('eve_sde', '0018_blueprintactivity_blueprintactivityproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='tax_rate_loot_items',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='EntryLootItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_items', to='allianceauth_pve.entry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='eve_sde.itemtype')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('entry', 'item'), name='unique_item_per_entry')],
            },
        ),
    ]
