# Generated by Django 5.2.12 on 2026-04-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0023_rotation_tax_rate_loot_items_entrylootitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationpreset',
            name='tax_rate_loot_items',
            field=models.FloatField(default=0, help_text='Tax rate for loot items in percentage'),
        ),
    ]
