# Generated by Django 5.2.17 on 2026-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0026_entrycharacter_site_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='site_scaling',
            field=models.CharField(choices=[('flat', 'Flat'), ('fabricator', 'Fabricator')], default='flat', max_length=16),
        ),
        migrations.AddField(
            model_name='entry',
            name='site_scaling_coefficient',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
