# Generated by Django 5.2.17 on 2026-10-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0027_entry_site_scaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='lock_roles_setup',
            field=models.BooleanField(default=False, help_text='Load the only roles setup automatically in every entry and prevent editing roles. Requires exactly 1 roles setup.'),
        ),
        migrations.AddField(
            model_name='rotationpreset',
            name='lock_roles_setup',
            field=models.BooleanField(default=False, help_text='Load the only roles setup automatically in every entry and prevent editing roles. Requires exactly 1 roles setup.'),
        ),
    ]
