# Generated by Django 5.2.17 on 2026-10-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_pve', '0028_lock_roles_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='site_scaling_coefficient',
        ),
    ]
